---
name: registripe#admin
---
LeftAndMain:
  extra_requirements_javascript:
    - registripe/javascript/cms.js
Payment:
  has_one:
    EventRegistration: EventRegistration
EventRegisterController:
  ticket_select_template: EventTicketSelector