---
name: registripe#admin
---
Payment:
  has_one:
    EventRegistration: EventRegistration
EventRegisterController:
  ticket_select_template: EventTicketSelector
EventRegistration:
  attendee_main_contact: true